### Criar produto
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "nome": "Mouse",
  "preco": 80
}

### Listar produtos
GET http://localhost:3000/produtos

### Criar pedido
POST http://localhost:3000/pedidos
Content-Type: application/json

{
  "produtoId": 2,
  "quantidade": 2
}

### Listar pedidos
GET http://localhost:3000/pedidos